### ISSUE TITLE
Unable to add integration - Unexpected error

### ISSUE THREAD

**Issue by Srkwithlove** [Hyundai-Kia-Connect/kia_uvo#643] opened 2023-05-14 10:24 UTC
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**

Canada 
Kia Sorento 2022

**Version of the integration**
2.10

HA 2023.5.2 

**Describe the bug**

Unable to add integration. Getting "unexpected error" when I put the credentials 

**Debug logs if an error occurred**

Outlined here: https://github.com/fuatakgun/kia_uvo/blob/master/README.md

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by cdnninja** [comment] 2023-05-14 14:29
Could you get the error from the logs?

**Comment by Srkwithlove** [comment] 2023-05-14 15:40
See below:

This error originated from a custom integration.

Logger: custom_components.kia_uvo.config_flow
Source: custom_components/kia_uvo/config_flow.py:63
Integration: Kia Uvo / Hyundai Bluelink (documentation, issues)
First occurred: 06:13:48 (3 occurrences)
Last logged: 11:37:13

Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py",
line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py",
line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py",
line 1042, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py",
line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line
449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line
493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line
489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py",
line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py",
line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='kiaconnect.ca',
port=443): Max retries exceeded with url: /tods/api/lgn (Caused by
SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type
(_ssl.c:1007)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/config_flow.py", line 159, in
async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/kia_uvo/config_flow.py", line 63, in
validate_input
    token: Token = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58,
in run
    result = self.fn(*self.args, **self.kwargs)
  File
"/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiCA.py",
line 138, in login
    response = self.sessions.post(url, json=data, headers=headers)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line
635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line
587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line
701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line
563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='kiaconnect.ca',
port=443): Max retries exceeded with url: /tods/api/lgn (Caused by
SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type
(_ssl.c:1007)')))

**Comment by cdnninja** [comment] 2023-05-14 18:48
What platform are you running on?

**Comment by Srkwithlove** [comment] 2023-05-15 21:34
Home Assistant on Raspberry Pi.

Ayaz

**Comment by cdnninja** [comment] 2023-05-15 22:09
Is this on core on some other OS?

**Comment by cdnninja** [comment] 2023-05-16 02:02
To confirm your not using core?  Core would be the native approach on pi.

**Comment by Srkwithlove** [comment] 2023-05-16 09:20
Not sure what changes now but I tried adding integration again and it got added successfully.

 However I am getting below error now:

This error originated from a custom integration.

Logger: custom_components.kia_uvo.coordinator
Source: custom_components/kia_uvo/coordinator.py:166
Integration: Kia Uvo / Hyundai Bluelink (documentation, issues)
First occurred: 05:16:00 (3 occurrences)
Last logged: 05:17:20

Unexpected error fetching kia_uvo data: Server returned: 'We're sorry, but your request could not be processed. Please try again. If the issue persists call Customer assistance at 1-877-542-2886.'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/kia_uvo/coordinator.py", line 107, in _async_update_data
    await self.async_check_and_refresh_token()
  File "/config/custom_components/kia_uvo/coordinator.py", line 166, in async_check_and_refresh_token
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 120, in check_and_refresh_token
    self.initialize()
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 64, in initialize
    self.token: Token = self.api.login(self.username, self.password)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiCA.py", line 125, in login
    self._check_response_for_errors(response)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiCA.py", line 115, in _check_response_for_errors
    raise APIError(f"Server returned: '{response['error']['errorDesc']}'")
hyundai_kia_connect_api.exceptions.APIError: Server returned: 'We're sorry, but your request could not be processed. Please try again. If the issue persists call Customer assistance at 1-877-542-2886.'

**Comment by cdnninja** [comment] 2023-05-20 20:56
You are getting server errors for some reason.   Does the native app work for you?

**Comment by Kagey-cmd** [comment] 2023-06-23 20:18
This is a "me too" comment. I'm unable to install the integration via UI.

**Comment by cdnninja** [comment] 2023-06-25 21:24
Happy to work on this but will need some install details.

**Comment by cdnninja** [comment] 2023-06-25 21:24
@kagey-cmd

**Comment by Kagey-cmd** [comment] 2023-06-26 16:34
Oh, I was just flagging #635 as a potential duplicate of this issue. Did I get the syntax wrong?
In any case, I got here because I was getting what appeared to be the same installation errors. Took a couple of retries and reboots of Hass, but it eventually worked. All good now.

**Comment by cdnninja** [comment] 2023-06-26 18:52
Good to hear.  Yes I saw your note as a email notification but it was missing when I looked.

**Comment by Madifor1972** [comment] 2023-06-30 16:36
Integration doesn’t work,
Get the following info in the log files.

Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.kia_uvo.config_flow
Source: custom_components/kia_uvo/config_flow.py:63 
Integration: Kia Uvo / Hyundai Bluelink (documentation, issues) 
First occurred: 18:31:49 (2 occurrences) 
Last logged: 18:32:21

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/config_flow.py", line 159, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/kia_uvo/config_flow.py", line 63, in validate_input
    token: Token = await hass.async_add_executor_job(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 198, in login
    device_id = self._get_device_id(stamp)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1104, in _get_device_id
    _check_response_for_errors(response)
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 110, in _check_response_for_errors
    raise APIError(f"Server returned: '{response['resMsg']}'")
hyundai_kia_connect_api.exceptions.APIError: Server returned: 'Invalid request body - Invalid parameter.'
 The natvice Bluelink app works fine with same credentials…

please advise.

**Comment by fuatakgun** [comment] 2023-06-30 16:53
@Madifor1972 please check open issues first

**Comment by cdnninja** [comment] 2023-07-03 18:53
Please try again on latest version and let us know.

**Closed by cdnninja** 2023-07-03 18:53 UTC

**Comment by Madifor1972** [comment] 2023-07-04 18:08
Successfully added the integration , great job.
