### ISSUE TITLE
Config Not Ready: 'intUserId' error

### ISSUE THREAD

**Issue by tobiasbrage** [Hyundai-Kia-Connect/kia_uvo#622] opened 2023-04-06 22:42 UTC
As of today the integration stopped working. It just gives me the error "Config Not Ready: 'intUserId'".
The BlueLink app works just fine.

Here's a snippet from the log:

Unexpected error fetching kia_uvo data: 'intUserId'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 203, in login
    authorization_code = self._get_authorization_code_with_redirect_url(
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1146, in _get_authorization_code_with_redirect_url
    parsed_url = urlparse(response["redirectUrl"])
KeyError: 'redirectUrl'

**Comment by cdnninja** [comment] 2023-04-06 22:49
Duplicate of existing issue.   Closing.

**Closed** 2023-04-06 22:49 UTC
