### ISSUE TITLE
Error when Lock / Unlock car from lock entity

### ISSUE THREAD

**Issue by JordanM1738** [Hyundai-Kia-Connect/kia_uvo#588] opened 2023-02-04 23:50 UTC
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
Canada / Hyundai

**Version of the integration**
v2.5.8

**Describe the bug**
When I try to lock / unlock my car from the lock card or directly from the entity lock.santa_fe_door_lock i have the error described bellow.
But when I call service kia_uvo.lock / kia_uvo.unlock from dev tools in HA it works well.
All other features works very well.

Thanks

**Debug logs if an error occurred**

Logger: homeassistant.components.websocket_api.http.connection
Source: components/lock/__init__.py:105
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 17:52:50 (2 occurrences)
Last logged: 17:59:06

[547302042272] HyundaiKiaConnectLock.async_unlock() got an unexpected keyword argument 'entity_id'
[547348713760] HyundaiKiaConnectLock.async_unlock() got an unexpected keyword argument 'entity_id'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1787, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1824, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 681, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 968, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 721, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/lock/__init__.py", line 105, in _async_unlock
    await entity.async_unlock(**service_call.data)
TypeError: HyundaiKiaConnectLock.async_unlock() got an unexpected keyword argument 'entity_id'

**To Reproduce**
Go to entity and try to lock or unlock car.
An error occurred

**Expected behavior**
Go to entity and try to lock or unlock car.
The car must be locked / unlocked

**Screenshots**
<img width="550" alt="image" src="https://user-images.githubusercontent.com/85708647/216794217-28dcad43-b8d0-434d-879b-fa2ad9c7df2a.png">

**Additional context**

**Comment by cdnninja** [comment] 2023-02-05 00:11
This is a duplicate of another issue.   Could you redownload in HACS and for version select master?

**Closed** 2023-02-05 02:14 UTC
