### ISSUE TITLE
Unable to log in even after a reinstall, 

### ISSUE THREAD

**Issue by miimikko** [Hyundai-Kia-Connect/kia_uvo#619] opened 2023-04-04 08:13 UTC
**Region and Brand of car**
EU/Kia EV6

**Version of the integration**
2.6.1

**Describe the bug**
Can not login, even after deleting the integration.

**Debug logs if an error occurred**

This was the error before reinstall:
`
Logger: custom_components.kia_uvo.coordinator
Source: custom_components/kia_uvo/coordinator.py:166
Integration: Hyundai / Kia Connect ([documentation](https://github.com/fuatakgun/kia_uvo), [issues](https://github.com/fuatakgun/kia_uvo/issues))
First occurred: 5:02:59 AM (38 occurrences)
Last logged: 9:52:01 AM
Unexpected error fetching kia_uvo data: 'int_user_id'

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 203, in login
    authorization_code = self._get_authorization_code_with_redirect_url(
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1146, in _get_authorization_code_with_redirect_url
    parsed_url = urlparse(response["redirectUrl"])
KeyError: 'redirectUrl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/kia_uvo/coordinator.py", line 107, in _async_update_data
    await self.async_check_and_refresh_token()
  File "/config/custom_components/kia_uvo/coordinator.py", line 166, in async_check_and_refresh_token
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 121, in check_and_refresh_token
    self.token: Token = self.api.login(self.username, self.password)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 208, in login
    authorization_code = self._get_authorization_code_with_form(
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1239, in _get_authorization_code_with_form
    intUserId = "".join(parse_qs(parsed_url.query)["int_user_id"])
KeyError: 'int_user_id'
`

**To Reproduce**
Delete integration and freshly install it again

**Expected behavior**
Log in should succeed

**Screenshot**
![image](https://user-images.githubusercontent.com/128098110/229730138-cb7ae6b3-40b1-4ce2-b459-4c8f41db74c3.png)

**Comment by hmmbob** [comment] 2023-04-04 08:36
Duplicate of #618

**Closed** 2023-04-06 22:49 UTC
