### ISSUE TITLE
2.0.x loses all services after some time

### ISSUE THREAD

**Issue by zadigre** [Hyundai-Kia-Connect/kia_uvo#467] opened 2022-12-01 14:51 UTC
I'm not sure when it started exactly... 
but after some time, 2.0.x loses all services... no service are available for this integration (no service in developper tools and unknown services in my scripts/automations). 
Sensors still work fine. 
I don't know if it's a bug with HA or the integration. I'm running latest HA stable.
I have to restart HA to get this working... only reloading the integration is not enough. 

see below error when trying to start climate this morning. 
and also errors following the integration reload. 
there's no other error in the log that might tell us what is going on. 

```
2022-12-01 07:05:00.038 ERROR (MainThread) [homeassistant.components.script.kona_chauffage_continue] KONA - Climat Continue: Choose at step 1: choice 1: Repeat at step 1: Error executing script. Service not found for call_service at pos 1: Unable to find service kia_uvo.start_climate
2022-12-01 07:05:00.045 ERROR (MainThread) [homeassistant.components.script.kona_chauffage_continue] KONA - Climat Continue: Choose at step 1: choice 1: Error executing script. Service not found for repeat at pos 1: Unable to find service kia_uvo.start_climate
2022-12-01 07:05:00.053 ERROR (MainThread) [homeassistant.components.script.kona_chauffage_continue] KONA - Climat Continue: Error executing script. Service not found for choose at pos 1: Unable to find service kia_uvo.start_climate
2022-12-01 07:05:00.064 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 484, in _async_run
return await self.script.async_run(script_vars, context)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1524, in async_run
await asyncio.shield(run.async_run())
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 409, in async_run
await self._async_step(log_exceptions=False)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 453, in _async_step
self._handle_exception(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 476, in _handle_exception
raise exception
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 896, in _async_choose_step
await self._async_run_script(script)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1029, in _async_run_script
await self._async_run_long_action(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 648, in _async_run_long_action
long_task.result()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1524, in async_run
await asyncio.shield(run.async_run())
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 409, in async_run
await self._async_step(log_exceptions=False)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 453, in _async_step
self._handle_exception(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 476, in _handle_exception
raise exception
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/trace.py", line 252, in async_wrapper
await func(*args)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 813, in _async_repeat_step
await async_run_sequence(iteration, extra_msg)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 795, in async_run_sequence
await self._async_run_script(script)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1029, in _async_run_script
await self._async_run_long_action(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 648, in _async_run_long_action
long_task.result()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1524, in async_run
await asyncio.shield(run.async_run())
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 409, in async_run
await self._async_step(log_exceptions=False)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 453, in _async_step
self._handle_exception(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 476, in _handle_exception
raise exception
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1691, in async_call
raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service kia_uvo.start_climate
```

```
2022-12-01 08:42:36.268 WARNING (MainThread) [homeassistant.core] Unable to remove unknown service kia_uvo/update
2022-12-01 08:42:36.272 WARNING (MainThread) [homeassistant.core] Unable to remove unknown service kia_uvo/force_update
2022-12-01 08:42:36.275 WARNING (MainThread) [homeassistant.core] Unable to remove unknown service kia_uvo/lock
2022-12-01 08:42:36.277 WARNING (MainThread) [homeassistant.core] Unable to remove unknown service kia_uvo/unlock
2022-12-01 08:42:36.279 WARNING (MainThread) [homeassistant.core] Unable to remove unknown service kia_uvo/stop_climate
2022-12-01 08:42:36.282 WARNING (MainThread) [homeassistant.core] Unable to remove unknown service kia_uvo/start_climate
2022-12-01 08:42:36.284 WARNING (MainThread) [homeassistant.core] Unable to remove unknown service kia_uvo/start_charge
2022-12-01 08:42:36.286 WARNING (MainThread) [homeassistant.core] Unable to remove unknown service kia_uvo/stop_charge
2022-12-01 08:42:36.288 WARNING (MainThread) [homeassistant.core] Unable to remove unknown service kia_uvo/set_charge_limits
```

**Comment by cdnninja** [comment] 2022-12-01 20:52
I haven't seen this one before.  What version of home assistant are you running and what platform?

**Comment by zadigre** [comment] 2022-12-01 21:09
This is on Home Assistant OS. 

Home Assistant 2022.11.5
Supervisor 2022.11.2
Operating System 9.3
Frontend 20221108.0 - latest

I was with 2022.11.4 with same problem. 

this happened more than once. first time, I just rebooted and didn't check log... after a few times, I decided to do a bug report even if there's nothing in log showing what's wrong.

**Comment by cdnninja** [comment] 2022-12-01 21:34
I will spend some more googling. I am also in Canada and haven't seen this yet.   Other spots I found this on google don't pinpoint the issue. Some of the threads trailed off.  Others blamed another integration.   Not clear so more research is needed.

**Comment by zadigre** [comment] 2022-12-01 21:47
really weird. I checked other integrations... and it looks like only this integration loses the services. 
I'll check again next time I see the problem.

**Comment by zadigre** [comment] 2022-12-02 02:48
happened again... 
all services were apparently available... but it wasn't responding to force update (data in the log... but sensors not updated). 
start climate was giving me an error in the myhyundai app. 
restarted myhundai. last updated finally updated... but service were not available after reboot (no sure if it was right after a reboot as I didn't check right away). 

I feel 2.0.36 was much more stable. 
I'll downgrade and see if this happens again

**Comment by zadigre** [comment] 2022-12-02 19:01
It's happening on 2.0.36 too. 
downgraded to 2.0.35 to see how it goes.

**Comment by cdnninja** [comment] 2022-12-03 00:11
Prior in the logs I am interested to see what happens. I suspect we will need home assistant debug logging enabled too but that could be a lot of logs.

**Comment by zadigre** [comment] 2022-12-03 01:18
I currently have this configured for logger:
logger:
  default: critical
  logs:
    custom_components.kia_uvo: debug
    hyundai_kia_connect_api: debug

I'll keep 2.0.35 at least until tomorrow afternoon/night if everything goes well and go back to latest 2.0.x.

for which other components would you like to have the debug for ?

**Comment by zadigre** [comment] 2022-12-04 01:09
for you information, I didn't lose any service with 2.0.35. I'm installation 2.0.40 now to see and it's doing.

**Comment by cdnninja** [comment] 2022-12-04 03:35
Prior to losing the service any calls from kia_uvo?   If you can run 2.0.35 and edit the manifest file to switch the API to 1.42.1 and see if that has the issue it will narrow down what side this is on.    API or the integration.

**Comment by zadigre** [comment] 2022-12-04 11:02
I wasn’t able to narrow it down to a specific call or action… I knew services were lost when last updated at wasn’t updating and when one of my script failed. 

2.0.40 is running fine since yesterday.
Besides restoring my backup, how do I reinstall 2.0.35 if it’s no longer available in the redownload menu?

**Comment by cdnninja** [comment] 2022-12-04 21:18
The files can be copied manually.  That being said, the big change between .35 and now is the number (SOC) sliders.   So lets do this. 

Can you edit the init.py file in your install?  Go and put a number sign in front of the number entity in this line: https://github.com/Hyundai-Kia-Connect/kia_uvo/blob/018378ef680b044d08e4b005f7dcb131087ecdc5/custom_components/kia_uvo/__init__.py#L26

This will disable the number platform and remove the SOC senser.  If you do this on .40 it will tell us if that is the cause of the errors.   To edit I find using the smb add on is the easier way.

**Comment by zadigre** [comment] 2022-12-05 04:15
I’ll do it next time it crashes…
It has been ok for the whole day… even changing the AC or DC charge limit did not crash it.

**Comment by zadigre** [comment] 2022-12-06 02:34
Still running fine after nearly 24 hours.

**Comment by zadigre** [comment] 2022-12-07 18:26
still running fine with 2.0.41... 
it appears something has ben fixed in 2.0.40... or it was just a fluke with something else on my system. 

I guess we can close this unless you want to keep it opened for a few days.

**Comment by cdnninja** [comment] 2022-12-07 19:04
Maybe - .40 had the following: 

https://github.com/Hyundai-Kia-Connect/kia_uvo/releases/tag/v2.0.40

**Comment by cdnninja** [comment] 2022-12-07 19:04
Lets close it out.  Feel free to comment here if it returns and we can re-open.

**Closed as completed by cdnninja** 2022-12-07 19:04 UTC
