### ISSUE TITLE
Connection to Hyundai EU suddenly not working

### ISSUE THREAD

**Issue by Taomyn** [Hyundai-Kia-Connect/kia_uvo#618] opened 2023-04-04 07:19 UTC
**Region and Brand of car**
EU Hyundai

**Version of the integration**
2.6.1

**Describe the bug**
All was well then suddenly the integration has stopped working with errors being logged

**Debug logs if an error occurred**

[home-assistant_kia_uvo_2023-04-04T07-09-01.527Z.log](https://github.com/Hyundai-Kia-Connect/kia_uvo/files/11145682/home-assistant_kia_uvo_2023-04-04T07-09-01.527Z.log)

**Screenshots**

![image](https://user-images.githubusercontent.com/4365929/229717006-6244af91-155c-49d3-ae0e-2cd40744f327.png)

**Additional context**
The app on my Android phone is working fine

**Comment by flight82** [comment] 2023-04-04 07:39
Since yesterday at 18.00 CET I have problem of connection with KIA account

```
Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 203, in login
    authorization_code = self._get_authorization_code_with_redirect_url(
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1146, in _get_authorization_code_with_redirect_url
    parsed_url = urlparse(response["redirectUrl"])
KeyError: 'redirectUrl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/config_flow.py", line 159, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/kia_uvo/config_flow.py", line 63, in validate_input
    token: Token = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 208, in login
    authorization_code = self._get_authorization_code_with_form(
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1239, in _get_authorization_code_with_form
    intUserId = "".join(parse_qs(parsed_url.query)["int_user_id"])
KeyError: 'int_user_id'

```

**Comment by pos-ei-don** [comment] 2023-04-04 07:48
Same here

**Comment by JackoAmmerlaan** [comment] 2023-04-04 07:49
Same problem here. I already tried to remove integration and add it again. Some error. App on Ios is working.

**Comment by Rob57a** [comment] 2023-04-04 10:08
Same error

**Comment by RoMe82** [comment] 2023-04-04 11:31
Same problem here

**Comment by hweckstr** [comment] 2023-04-04 11:55
I also have the same error.

**Comment by jiristepan** [comment] 2023-04-04 12:37
Same problem after update integration to new version v2.6.1

**Comment by mattevans111** [comment] 2023-04-04 12:38
I also have almost the same error. "Retrying setup: Config Not Ready: 'int_user_id'"

**Comment by elektrinis** [comment] 2023-04-04 16:12
App does not work for me as well. "the vehicle does not respond to the service you requested"
They must be fed up with 12V battery replacements.

**Comment by cdnninja** [comment] 2023-04-04 16:17
@elektrinis interesting 

Could other check if the native app works?

**Comment by elektrinis** [comment] 2023-04-04 16:25
Restarted the phone and tried again. Same thing. Three times in a row.
Switched to other internet provider and then it worked. Switched back to home wifi and it worked as well. Not sure what the problem was.
HA integration still does not work `Config Not Ready: 'intUserId'`

I noticed that it was very slow and unresponsive for a few days.

**Comment by jiristepan** [comment] 2023-04-04 16:30
> @elektrinis interesting
> 
> Could other check if the native app works?

Yes the native application works. I tries login/logout.
Using hyundai in EU.

**Comment by Maaxion** [comment] 2023-04-04 16:31
Issue is not related to this repo., but to the hyundai_kia_connect_api repo.

See [issue #309 over there ](https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/issues/309)

**Comment by flight82** [comment] 2023-04-04 19:01
> @elektrinis interesting
> 
> Could other check if the native app works?

The native app is working for me

**Comment by fuatakgun** [comment] 2023-04-04 19:51
https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/issues/309#issuecomment-1496509407

**Comment by 4homeassistant** [comment] 2023-04-04 23:31
A couple of minutes ago I saw the same issue (Hyundai EU) while the app is still working. Are they rolling out the new stamp creation logic for the EUcc API to block non-regular API calls as we heard earlier this year?
@fuatakgun @cdnninja

**Comment by cromelex** [comment] 2023-04-05 07:17
Having the same error, this is what I am seeing on the logs:

2023-04-05 08:14:37.979 ERROR (MainThread) [custom_components.kia_uvo.coordinator] Unexpected error fetching kia_uvo data: 'int_user_id'
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 203, in login
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1146, in _get_authorization_code_with_redirect_url
File "/config/custom_components/kia_uvo/coordinator.py", line 107, in _async_update_data
File "/config/custom_components/kia_uvo/coordinator.py", line 166, in async_check_and_refresh_token
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 208, in login
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1239, in _get_authorization_code_with_form

**Comment by a-schiffer** [comment] 2023-04-05 07:25
Looking into the debugger, this is what happens:
![image](https://user-images.githubusercontent.com/129929269/230010569-e42b31a4-a1b7-4bd2-bbda-197097fe1aee.png)
(Of course, the credentials I use worked fine two days, and I didn't change anything)

**Comment by a-schiffer** [comment] 2023-04-05 07:32
And then the code goes into the fallback path using _get_authorization_code_with_form(...), but the parsed_url doesn't contain "intUserId" which causes the final exception.
![image](https://user-images.githubusercontent.com/129929269/230011885-f539b769-d13a-4dac-9871-f79c52fcf8d1.png)

**Comment by hmmbob** [comment] 2023-04-05 07:38
The problem is in the API component that this Home Assistant component uses.

See https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/issues/309

**Comment by HMvdZijden** [comment] 2023-04-05 08:03
Same her, log:
Error setting up entry h.m.v.d.zijden@gmail.com for kia_uvo
Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 125, in login
    self.authorization_code = self.get_authorization_code_with_redirect_url()
  File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 247, in get_authorization_code_with_redirect_url
    parsed_url = urlparse(response["redirectUrl"])
KeyError: 'redirectUrl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/kia_uvo/__init__.py", line 218, in async_setup_entry
    await update(dt_util.utcnow())
  File "/config/custom_components/kia_uvo/__init__.py", line 187, in update
    await vehicle.refresh_token()
  File "/config/custom_components/kia_uvo/Vehicle.py", line 178, in refresh_token
    await self.hass.async_add_executor_job(self.login)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/kia_uvo/Vehicle.py", line 253, in login
    self.token = self.kia_uvo_api.login()
  File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 127, in login
    self.authorization_code = self.get_authorization_code_with_form()
  File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 340, in get_authorization_code_with_form
    intUserId = "".join(parse_qs(parsed_url.query)["int_user_id"])
KeyError: 'int_user_id'

**Comment by booknownick** [comment] 2023-04-05 09:16
also receiving this error.

**Comment by carlosvalin** [comment] 2023-04-05 12:10
I have the same problems in HA, app Kia connect works fine

**Comment by mattiaslang** [comment] 2023-04-05 13:01
Same.
I have the same problems in HA, app Kia connect works fine.

**Comment by DJBenson** [comment] 2023-04-06 13:44
> [Hyundai-Kia-Connect/hyundai_kia_connect_api#309 (comment)](https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/issues/309#issuecomment-1496509407)
> 
> Summary: I am not able to replicate the issue locally until i have access to account credentials having the problem.
> 
> Until then, please share full debug logs over email ([fuatakgun@gmail.com](mailto:fuatakgun@gmail.com)) after redacting any sensitive information.

Have emailed you about credentials.

**Comment by DJBenson** [comment] 2023-04-06 13:46
> App does not work for me as well. "the vehicle does not respond to the service you requested" They must be fed up with 12V battery replacements.

I would not be surprised one bit if Hyundai throw the baby out with the bath water in a bid to "solve" the 12v battery issues - however my experience is even those not using "unauthorised" apps are still suffering battery drain which they'll find out if they do ban the 3rd party apps and are still left with a problem. They really need to fix the software so that **_massive_** battery under the car can charge the **_tiny_** battery under the bonnet/hood.

**Comment by Bluhme1** [comment] 2023-04-06 17:49
So, will this be the end of the Hyundai car in HA. I’ll miss it

**Comment by cdnninja** [comment] 2023-04-06 18:59
A few people are working to reverse engineer this again.  It may not be the end.

I don't live in the eu so can't help much.  

I know eu Hyundai Kia wants us not to use this but also haven't reached out to discuss ways we can lesson load if truly and issue.

**Comment by povlhp** [comment] 2023-04-07 05:05
Can't be 12V battery issue. 
They can fix that server side. I.e. have server deliver only cached values. Handle force update different etc. 

And my 12V battery was never below 80% in my 14 months with EV6.

**Comment by elektrinis** [comment] 2023-04-07 05:09
> And my 12V battery was never below 80% in my 14 months with EV6.

Mine died on Ioniq5 and was replaced. I noticed the car draws 18amps for couple of minutes with every forced poll. This is a design flaw within the car itself.

**Comment by pierpaolo1972** [comment] 2023-04-07 14:58
I have the same problems with my Kona

**Comment by dlysnes** [comment] 2023-04-07 20:30
Seems these guys did an update. Sth to make us of? I haven't tested bluelinky for a while, though. https://github.com/Hacksore/bluelinky/commits/master

**Comment by Bluhme1** [comment] 2023-04-07 21:34
@fuatakgun Can this be used for the HA integration?

**Comment by fuatakgun** [comment] 2023-04-07 21:39
This is on my list for this weekend. I see there is also a pr from @cdnninja so you can check it locally.

Everything we will do will be random because we are not facing the problem ourselves so we cannot guarantee if it is working until you test it locally.

Until that moment, I am asking everyone to give a try this;
- create a secondary brand new account with a different phone number
- share your car with new account
- remove and add back integration with new account credentials
I am hoping that this will resolve it temporarily until we have a better fix in place. Please let us know the results.

**Comment by Noobalicious** [comment] 2023-04-08 00:10
I'm in the US, and it stopped working for me today.  But it coincided with upgrading HA to version 2023.4.1, in case that's something.

**Comment by cdnninja** [comment] 2023-04-08 00:13
> I'm in the US, and it stopped working for me today.  But it coincided with upgrading HA to version 2023.4.1, in case that's something.

That is unrelated to this thread.  

Please open a new issue.

**Comment by RoMe82** [comment] 2023-04-08 09:58
> This is on my list for this weekend. I see there is also a pr from @cdnninja so you can check it locally.
> 
> Everything we will do will be random because we are not facing the problem ourselves so we cannot guarantee if it is working until you test it locally.
> 
> Until that moment, I am asking everyone to give a try this;
> 
>     * create a secondary brand new account with a different phone number
> 
>     * share your car with new account
> 
>     * remove and add back integration with new account credentials
>       I am hoping that this will resolve it temporarily until we have a better fix in place. Please let us know the results.

Hi, 

I am in Europe and have an Ioniq 5. Based on your request I opened a new account with a different email and phone number. Then I requested the share of my car from my old account. I deleted the Hyundai/Kia integration and reloaded from HACS. When I registered with the new userid an "unknown" error came up. No error code, no further message. Repeating that procedure twice, without the account registration, led to the same issue.

**Comment by andig** [comment] 2023-04-08 10:24
Bluelinky seems to have released a fix.

**Comment by cdnninja** [comment] 2023-04-08 14:00
Could someone update from master and let us know if it is resolved?  Credit goes to @Danielhiversen

**Comment by vonsh** [comment] 2023-04-08 14:16
I did an update from master, but it failed with a different error. 

The log shows:

```
Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 203, in login
    authorization_code = self._get_authorization_code_with_redirect_url(
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1147, in _get_authorization_code_with_redirect_url
    parsed_url = urlparse(response["redirectUrl"])
KeyError: 'redirectUrl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/config_flow.py", line 159, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/kia_uvo/config_flow.py", line 63, in validate_input
    token: Token = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 208, in login
    authorization_code = self._get_authorization_code_with_form(
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1245, in _get_authorization_code_with_form
    parsed_url = urlparse(response["redirectUrl"])
KeyError: 'redirectUrl'
```

**Comment by tiramiseb** [comment] 2023-04-08 14:22
I am in France. I have a Hyundai Ioniq 38.
I updated from master using HACS.
Error disappeared aftr update, I have access to my car's data.

**Comment by RustyDust** [comment] 2023-04-08 14:33
Location: Germany/Europe
I see the same error as @vonsh
Tell me where to send the debug log to and I'll send it.
Excerpt:
```
DEBUG:hyundai_kia_connect_api.KiaUvoApiEU:hyundai_kia_connect_api - silentsignin Response {'errId': 'b814be7e-ccd8-4f39-84a2-3bb9919d0645', 'errCode': '4010', 'errMsg': 'Require authentication'}
```

**Comment by Flight777** [comment] 2023-04-08 14:46
> Could someone update from master and let us know if it is resolved? Credit goes to @Danielhiversen

Worked from my side:

Via HACS > Redownload then "Show beta versions" and select master.

After fulle Home Assistant server reboot (so not only reloading integration), it works again :)

**Comment by bumperboy** [comment] 2023-04-08 14:47
I installed again the integration using the master version and I'm again able to access the car's info in home assistant. For info, I have an ioniq 5 in BE

**Comment by Bluhme1** [comment] 2023-04-08 15:05
Fantastic. Did a reinstall from Hacs ("master") and everything works. Living in Denmark and using a Kona Electric.

Thank you very much guys 🥇 

Is there anything we should do to avoid similar actions from Hyundai/kia again?

**Comment by pos-ei-don** [comment] 2023-04-08 15:15
I Upgrade in HAcs to Master and it works! Thank you!

**Comment by cdnninja** [comment] 2023-04-08 15:23
> Fantastic. Did a reinstall from Hacs ("master") and everything works. Living in Denmark and using a Kona Electric.
> 
> 
> 
> Thank you very much guys 🥇 
> 
> 
> 
> Is there anything we should do to avoid similar actions from Hyundai/kia again?

Unfortunately they have a goal of cutting us out.  We know that through some posts here.  It will happen again and hopefully we can keep reverse engineering the changes.

**Comment by rindlerblabla** [comment] 2023-04-08 15:24
Hm. For me it is still not working. Redownloaded master version d73ef4b.

Have tried to add the integration again but get an unexpected error.

```
Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 203, in login
    authorization_code = self._get_authorization_code_with_redirect_url(
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1147, in _get_authorization_code_with_redirect_url
    parsed_url = urlparse(response["redirectUrl"])
KeyError: 'redirectUrl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/config_flow.py", line 159, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/kia_uvo/config_flow.py", line 63, in validate_input
    token: Token = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 208, in login
    authorization_code = self._get_authorization_code_with_form(
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1245, in _get_authorization_code_with_form
    parsed_url = urlparse(response["redirectUrl"])
KeyError: 'redirectUrl'

```

**Comment by erelke** [comment] 2023-04-08 15:28
Same "redirectUrl" error (Kia, EU) with new version.

**Comment by DragonQ** [comment] 2023-04-08 15:38
Same "Retrying setup: Config Not Ready: 'redirectUrl'" error with master branch here. Kia, UK/EU.

**Comment by cdnninja** [comment] 2023-04-08 15:43
> Same "Retrying setup: Config Not Ready: 'redirectUrl'" error with master branch here. Kia, UK/EU.

After a restart of home assistant?

**Comment by DragonQ** [comment] 2023-04-08 15:46
> > Same "Retrying setup: Config Not Ready: 'redirectUrl'" error with master branch here. Kia, UK/EU.
> 
> After a restart of home assistant?

Yes, reinstalled integration from master branch via HACS, restarted HA, then also tried reloading the integration.

**Comment by fuatakgun** [comment] 2023-04-08 16:00
Confirm that non-impacted flow is working fine as usual

**Comment by erelke** [comment] 2023-04-08 16:22
After several reboots and tries it works again! BUT with _old_ UVO account (2020), not with Kia account. My app works with Kia account registered in 2021!

**Comment by RustyDust** [comment] 2023-04-08 16:28
> Yes, reinstalled integration from master branch via HACS, restarted HA, then also tried reloading the integration.

Same here, still not working. See also [this post](https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/issues/309#issuecomment-1500923808). Since my account was created in January 2023 I believe @zulufoxtrot is right and whether the fix works or not really depends on when the account was created. [This post](https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/618#issuecomment-1500925834) also seems to confirm this suspicion.

**Comment by DragonQ** [comment] 2023-04-08 16:35
> > Same "Retrying setup: Config Not Ready: 'redirectUrl'" error with master branch here. Kia, UK/EU.
> 
> After a restart of home assistant?

Yes, reinstalled integration from master branch via HACS, restarted HA, then also tried reloading the integration.

> > Yes, reinstalled integration from master branch via HACS, restarted HA, then also tried reloading the integration.
> 
> Same here, still not working. See also [this post](https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/issues/309#issuecomment-1500923808). Since my account was created in January 2023 I believe @zulufoxtrot is right and whether the fix works or not really depends on when the account was created. [This post](https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/618#issuecomment-1500925834) also seems to confirm this suspicion.

My account is from September 2020 ish (an UVO account originally, later "converted" to a Kia account).

**Comment by zulufoxtrot** [comment] 2023-04-08 17:16
A PR is out for newer accounts: https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/317
Should fix the "redirectUrl" bug.
I need testers with both old and new accounts to validate it.

**Comment by erelke** [comment] 2023-04-08 17:18
> > Same here, still not working. See also [this post](https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/issues/309#issuecomment-1500923808). Since my account was created in January 2023 I believe @zulufoxtrot is right and whether the fix works or not really depends on when the account was created. [This post](https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/618#issuecomment-1500925834) also seems to confirm this suspicion.
> 
> My account is from September 2020 ish (an UVO account originally, later "converted" to a Kia account).

With "converted" account I get the error, but with old, original UVO account works fine.

**Comment by RustyDust** [comment] 2023-04-08 17:30
> A PR is out for newer accounts: [Hyundai-Kia-Connect/hyundai_kia_connect_api#317](https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/317)
> Should fix the "redirectUrl" bug.
> I need testers with both old and new accounts to validate it.

Works with my "new" account, unfortunately I don't haven an UVO account to test with.
Thanks anyway!

**Comment by Aketzu** [comment] 2023-04-08 17:40
> A PR is out for newer accounts: [Hyundai-Kia-Connect/hyundai_kia_connect_api#317](https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/317) Should fix the "redirectUrl" bug. I need testers with both old and new accounts to validate it.

clientid 572.. fixes the problem for me. Kia EU, account created April 2022

**Comment by 4homeassistant** [comment] 2023-04-08 18:16
Works again 😊
Account created in Dec 2023.

**Comment by markahon** [comment] 2023-04-08 18:19
> I installed again the integration using the master version and I'm again able to access the car's info in home assistant. For info, I have an ioniq 5 in BE. Thank you all

Same here. Reinstalled integration from master about 3 hours ago, old sensors and services started working after HA restart. My Bluelink account is quite recent, created in March/2023, just about one month ago.

**Comment by a-schiffer** [comment] 2023-04-08 18:41
I use the Python module directly, and also for me the fix works perfectly. Thanks a lot for getting this fixed so quickly.
And - as Software Engineer myself - I really love fixes that mainly consist of removing code :)  Nicely done!

@4homeassistant : I wish I also could use an account that was created in the future :P

**Comment by ot3** [comment] 2023-04-08 18:46
Also using the module directly but unfortunately 3.1.6. does not work for me:
```Traceback (most recent call last):
  File "/home/pi/miniconda3/envs/kia/lib/python3.9/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 203, in login
    authorization_code = self._get_authorization_code_with_redirect_url(
  File "/home/pi/miniconda3/envs/kia/lib/python3.9/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1147, in _get_authorization_code_with_redirect_url
    parsed_url = urlparse(response["redirectUrl"])
KeyError: 'redirectUrl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/live/kia.py", line 819, in <module>
    main()
  File "/home/pi/live/kia.py", line 806, in main
    fetch_kia('SNAPSHOT')
  File "/home/pi/live/kia.py", line 567, in fetch_kia
    fetch_kia_and_store(session_mode)
  File "/home/pi/live/kia.py", line 541, in fetch_kia_and_store
    my_vehicle = fetch_vehicle()
  File "/home/pi/live/kia.py", line 162, in fetch_vehicle
    vm.check_and_refresh_token()
  File "/home/pi/miniconda3/envs/kia/lib/python3.9/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 118, in check_and_refresh_token
    self.initialize()
  File "/home/pi/miniconda3/envs/kia/lib/python3.9/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 62, in initialize
    self.token: Token = self.api.login(self.username, self.password)
  File "/home/pi/miniconda3/envs/kia/lib/python3.9/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 208, in login
    authorization_code = self._get_authorization_code_with_form(
  File "/home/pi/miniconda3/envs/kia/lib/python3.9/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1245, in _get_authorization_code_with_form
    parsed_url = urlparse(response["redirectUrl"])
KeyError: 'redirectUrl'
```

**Comment by zulufoxtrot** [comment] 2023-04-08 18:50
@ot3 https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/317 should fix your problem. We'll include it in the next release.

**Comment by RoMe82** [comment] 2023-04-08 18:52
Updated on Ioniq 5 in DE and it works again.

**Comment by dlysnes** [comment] 2023-04-08 19:16
Confirmed. Master works fine. Both Hyundai (Kona), and Kia (Niro). 2020 and 2021 accounts. Thanx a bunch, guys!! Much appreciated 🙏🏻

**Comment by zulufoxtrot** [comment] 2023-04-08 19:19
Great! Thanks for confirming. The fix has been merged, an automated release should be out soon.

**Comment by Boltify** [comment] 2023-04-08 19:22
Reinstalled "master" version, restarted HA but I'm facing the same issue. 
"Unexpected error"

**Comment by DragonQ** [comment] 2023-04-08 19:30
Master still doesn't work for me.

```2023-04-08 19:28:58.911 ERROR (MainThread) [custom_components.kia_uvo.coordinator] Unexpected error fetching kia_uvo data: 'redirectUrl'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 203, in login
    authorization_code = self._get_authorization_code_with_redirect_url(
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1147, in _get_authorization_code_with_redirect_url
    parsed_url = urlparse(response["redirectUrl"])
KeyError: 'redirectUrl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 250, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/kia_uvo/coordinator.py", line 107, in _async_update_data
    await self.async_check_and_refresh_token()
  File "/config/custom_components/kia_uvo/coordinator.py", line 166, in async_check_and_refresh_token
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 118, in check_and_refresh_token
    self.initialize()
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 62, in initialize
    self.token: Token = self.api.login(self.username, self.password)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 208, in login
    authorization_code = self._get_authorization_code_with_form(
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1245, in _get_authorization_code_with_form
    parsed_url = urlparse(response["redirectUrl"])
KeyError: 'redirectUrl'
```

**Comment by DavidBSteele** [comment] 2023-04-08 19:45
Installed master (through hacs) and restarted and all working for me.

Hyundai ionic 5 in UK
Account created: May 2022

Great work on this component and thank you! 🙏

**Comment by cdnninja** [comment] 2023-04-08 20:23
Another fix has been put in for select accounts.  Please download the latest and retry. It also has an actual release now so don't need to update from master.

**Comment by Mkay505** [comment] 2023-04-08 20:31
Thank you for the update. It works.
Great job 👍

**Comment by Boltify** [comment] 2023-04-08 20:31
2.7.0 works like a charm! thanks for all your work!

**Comment by erelke** [comment] 2023-04-08 20:32
> A PR is out for newer accounts: [Hyundai-Kia-Connect/hyundai_kia_connect_api#317](https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/317) Should fix the "redirectUrl" bug. I need testers with both old and new accounts to validate it.

I confirm, this work withboth  old (2020/UVO) and with new (Connect/2021) accounts!

**Comment by cdnninja** [comment] 2023-04-08 20:38
We have some reports of force updates not working still.  Could you test that?

**Comment by erelke** [comment] 2023-04-08 20:44
> We have some reports of force updates not working still. Could you test that?

forced update work fine for me (2.7.0, Kia, EU)

**Comment by SebastianSiegl** [comment] 2023-04-08 20:45
Can confirm - all back to normal. Account created Sept 22 - had the URL Problems but with the lastest reinstall everything works well again.

**Comment by JuergenEhret** [comment] 2023-04-08 20:49
Had the issue with my KIA and just wanted to write a bug report but saw that in the meanwhile an update is here ;-) Thx for the quick fix ... highly appreciated !!!

**Comment by 4homeassistant** [comment] 2023-04-08 22:39
> We have some reports of force updates not working still. Could you test that?

Works as expected @cdnninja 😊

**Comment by cdnninja** [comment] 2023-04-09 01:08
Awesome. I will close this!  Can re-open or have new issues if something comes up.

**Closed by cdnninja** 2023-04-09 01:08 UTC

**Comment by TraipZe** [comment] 2023-04-09 08:03
Thanks a lot for repair this 🙏

**Comment by alexfd** [comment] 2023-05-02 11:44
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/kia_uvo/__init__.py", line 51, in async_setup_entry
    coordinator = HyundaiKiaConnectDataUpdateCoordinator(hass, config_entry)
  File "/config/custom_components/kia_uvo/coordinator.py", line 67, in __init__
    language=hass.config.language,
AttributeError: 'Config' object has no attribute 'language'
```
Does this mean the plugin now depends on HA providing this 'language' feature, thus I have to update HA?

**Comment by cdnninja** [comment] 2023-05-02 14:06
Yes you need to update home assistant.
