### ISSUE TITLE
All sensor states report Unavailable

### ISSUE THREAD

**Issue by stintov** [Hyundai-Kia-Connect/kia_uvo#848] opened 2024-03-08 16:00 UTC
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
EU Kia EV9
**Version of the integration**
2.22.0

**Describe the bug**
All sensor states report Unavailable

**Screenshots**
![image](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/130797662/cb671c47-a5ac-4fa0-a373-deb4e799e9f1)

**Additional context**
The itegration has been working fine for over a week, but today for no reason all the sensors report "Unavailable" A restart of HA has not helped. The Kia Connect mobile app is working fine.

**Comment by renatkh** [comment] 2024-03-19 00:15
Same here. My integration failed to setup. When I turn on debugging and reload the integration, I can see that it successfully logs in, reads sensor data at towards the end of the logs I see this
```2024-03-19 00:11:33.513 DEBUG (SyncWorker_2) [hyundai_kia_connect_api.KiaUvoAPIUSA] hyundai_kia_connect_api - last_updated_at - before 20240318231355
2024-03-19 00:11:33.514 DEBUG (SyncWorker_2) [hyundai_kia_connect_api.KiaUvoAPIUSA] hyundai_kia_connect_api - last_updated_at - after 2024-03-18 23:13:55+00:00
2024-03-19 00:11:33.514 DEBUG (SyncWorker_2) [hyundai_kia_connect_api.KiaUvoAPIUSA] hyundai_kia_connect_api - SOC Levels couldn't be found. May not be an EV.
2024-03-19 00:11:33.514 DEBUG (SyncWorker_2) [hyundai_kia_connect_api.KiaUvoAPIUSA] hyundai_kia_connect_api - last_updated_at - before 20240318231355
2024-03-19 00:11:33.514 DEBUG (SyncWorker_2) [hyundai_kia_connect_api.KiaUvoAPIUSA] hyundai_kia_connect_api - last_updated_at - after 2024-03-18 23:13:55+00:00
2024-03-19 00:11:35.511 DEBUG (MainThread) [custom_components.kia_uvo.coordinator] Finished fetching kia_uvo data in 5.183 seconds (success: False)
```

**Comment by renatkh** [comment] 2024-03-19 00:21
This issue is the duplicate of #837

**Comment by csmracing** [comment] 2024-03-19 16:36
> I haven't investigated why yet, but it seems like it is the Geocoding API that is silently failing. Can you try to disable the "Enable Geolocation Entity using OpenStreetMap" option in the integration configuration?

I started experiencing this same problem within the last 24-48 hours.  As suggested, I disabled "Enable Geolocation Entity using OpenStreetMap" and now the integration is working again.

**Comment by alexwhittemore** [comment] 2024-03-19 22:04
Same experience: the integration stopped providing entities yesterday midday, about 24h ago, and disabling the geolocation entity config option immediately recovered normal operation.

**Comment by renatkh** [comment] 2024-03-20 00:13
Yes, disabling geolocation fixed the issue. Thanks @damz!

**Comment by Legrand5382** [comment] 2024-03-20 03:54
Same here, i disabled geolocation and now everything is fine 😊

**Comment by cdnninja** [comment] 2024-03-20 04:15
After you disable geolocation is lat long look correct?    When I manually test the geolocation API it has no issue. 

Here is an example API call to geo location: https://[nominatim.openstreetmap.org/reverse?lat=57&lon=-112&format=json&addressdetails=1&zoom=18&](https://nominatim.openstreetmap.org/reverse?lat=57&lon=-112&format=json&addressdetails=1&zoom=18&)

**Comment by alexwhittemore** [comment] 2024-03-20 13:58
Yes- the lag long entity remains accurate and up to date.

**Comment by przemekp833** [comment] 2024-03-25 16:33
excuse me guys, quite new with HA. How do I disable the "Enable Geolocation Entity using OpenStreetMap" option in the integration configuration? :) thanks

**Comment by alexwhittemore** [comment] 2024-03-26 01:34
> excuse me guys, quite new with HA. How do I disable the "Enable Geolocation Entity using OpenStreetMap" option in the integration configuration? :) thanks

Settings>Devices>Hyundai/Kia Connect, then on the one line that should exist for your kia account, click "Configure"

Uncheck "Enable Geolocation Entity using OpenStreetMap"

And don't feel bad, HA's UI can be desperately confusing if you don't already know all the implementation details of what you're trying to do, and sometimes if you do ;)

**Comment by cdnninja** [comment] 2024-03-26 02:42
Looks like we have two thread on this.   I put code in for lat Lon protection.  I could use debug logs from someone who has functional location entity to understand what's happening here.

**Comment by cdnninja** [comment] 2024-03-26 03:09
Lets track this in #853

**Closed by cdnninja** 2024-03-26 03:09 UTC

**Comment by przemekp833** [comment] 2024-03-26 06:22
Thanks for the information. I found it, but to be my surprise it was already unchecked and the integration is still not working, whether its checked or unchecked. Do you have any suggestions where to look further? Thanks
