### ISSUE TITLE
Unsafe legacy renegotiation disabled

### ISSUE THREAD

**Issue by nprez83** [Hyundai-Kia-Connect/kia_uvo#913] opened 2024-07-20 18:07 UTC
**Region and Brand of car**
USA, Kia Telluride

**Version of the integration**
2.26.0

**Describe the bug**
Some time in the last 1-2 days, the integration started not loading with the following error.

**Debug logs if an error occurred**
```
Failed setup, will retry: Config Not ready: HTTPSConnectionPool(host='api.owners.kia.com',port=443): Max retries exceeded with url: /apigw/v1/prof/authUser (Caused by SSLError(SSLError(1,'[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1000)')))
```

**To Reproduce**
Attempt to load integration

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/5b28abb0-f11f-4425-b33f-692bb14cb3b5)

**Additional context**

**Comment by cdnninja** [comment] 2024-07-20 18:22
Did you update your OS? Or anything else?

**Comment by npike** [comment] 2024-07-20 18:56
Same... No changes to my HAOS install.

**Comment by nprez83** [comment] 2024-07-20 19:08
Last time I updated before the problem started was on 7/10 (2024.7.2). I did updated to 2024.7.3 today, but the problem was already present. I usually check my dashboard daily, but I was pretty busy the past 2 days, so I'm pretty sure the issues started sometime yesterday/overnight.

**Comment by daubman** [comment] 2024-07-20 19:10
I noticed this just started happening after I updated HA Core from v2024.7.2 to v2024.7.3 - but I didn't check to see if it was happening as well before updating.

**Comment by daubman** [comment] 2024-07-20 19:16
This looks very similar to the issue just over a year ago - not sure why it would resurface now, though
https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/679

**Comment by daubman** [comment] 2024-07-20 19:32
If it helps debug anything, I noticed this from ~15 hours ago (EDT/GMT-4) - everything became "unavailable" at the same time:

> **Logbook**
> July 20, 2024
> My EV9 Door Lock became unavailable
> 12:07:42 AM - 15 hours ago

**Comment by nprez83** [comment] 2024-07-20 19:40
Was definitely happening before I updated to 2024.7.3. 15 hours ago makes sense.

**Comment by bryanjblake** [comment] 2024-07-20 20:04
I’m getting the same error. Says it went unavailable at 12:30am EST

**Comment by cdnninja** [comment] 2024-07-20 20:05
Last time it was Hyundai.  May need to put the same fix into Kia now.

**Comment by rgnet5** [comment] 2024-07-20 21:45
Getting the same error on a Kia Sorento.  Started after 2024.7.3 update.

**Comment by npike** [comment] 2024-07-20 21:55
> Last time it was Hyundai. May need to put the same fix into Kia now.

Yup seems like a reasonable theory. Looks like KiaUvoAPIUSA.py could be updated in a similar fashion.

**Comment by ianwood** [comment] 2024-07-20 22:18
Same error. No changes on my end.

**Comment by dethpickle** [comment] 2024-07-21 00:50
Same error, same symptoms, same timing. Kia EV9. No recent changes to HA.

**Comment by npike** [comment] 2024-07-21 03:27
> > Last time it was Hyundai. May need to put the same fix into Kia now.
> 
> Yup seems like a reasonable theory. Looks like KiaUvoAPIUSA.py could be updated in a similar fashion.

I've temporarily forked this HACS integration and the hyundai_kia_connect_api to make a quick fix while we wait for an official update :)

You can either manually change your custom_components/kia_uvo/manifest.json to use my temporary version of hyundai_kia_connect_api, or you can change your HACs repo to mine: https://github.com/npike/kia_uvo

```
"requirements": ["hyundai_kia_connect_api==3.22.0"],
```

changes to

```
"requirements": ["hyundai_kia_connect_api @ git+https://github.com/npike/hyundai_kia_connect_api.git@master"],
```

For the first option, you may have to gain shell access your HA (I am using HAOS) to uninstall the current version of the hyundai_kia_connect_api python library.  For me this looked like:

```
docker exec -it homeassistant /bin/bash
pip3 uninstall hyundai_kia_connect_api
(then restart HA)
```

**Comment by cdnninja** [comment] 2024-07-21 04:11
Thanks for submitting the fix.  I have merged it.

**Comment by mbowie** [comment] 2024-07-21 04:17
Confirmed resolved the behavior I was seeing here with the merged changes. Many thanks all!

**Comment by nprez83** [comment] 2024-07-21 12:34
Thank you @npike @cdnninja for the quick fix. All is well now.

**Closed** 2024-07-21 14:29 UTC
